useTabs: false
tabWidth: 4
semi: false
bracketSameLine: true
singleQuote: true
trailingComma: es5
printWidth: 120
plugins:
- prettier-plugin-svelte
overrides:
- files: "*.svelte"
  options:
    parser: svelte
